"""Canonical environment variable names used across Lore."""

from __future__ import annotations

AUDIT_DB_PATH = "LORE_AUDIT_DB_PATH"
ALLOW_INSECURE_DEV_SALT = "LORE_ALLOW_INSECURE_DEV_SALT"
ALLOW_STDIO_DEV = "LORE_ALLOW_STDIO_DEV"
COMPLIANCE_STRICT_MODE = "LORE_COMPLIANCE_STRICT_MODE"
DB_PATH = "LORE_DB_PATH"
DR_SNAPSHOT_DIR = "LORE_DR_SNAPSHOT_DIR"
EMBEDDING_DIM = "LORE_EMBEDDING_DIM"
EMBEDDING_MODEL = "LORE_EMBEDDING_MODEL"
EMBEDDING_PROVIDER = "LORE_EMBEDDING_PROVIDER"
EMBEDDING_WORKERS = "LORE_EMBEDDING_WORKERS"
EMBEDDING_TIMEOUT_SECONDS = "LORE_EMBEDDING_TIMEOUT_SECONDS"
ENABLE_AGENT_PERMISSIONS = "LORE_ENABLE_AGENT_PERMISSIONS"
ENABLE_MULTI_TENANT = "LORE_ENABLE_MULTI_TENANT"
ENABLE_SEMANTIC_DEDUP = "LORE_ENABLE_SEMANTIC_DEDUP"
ENCRYPTION_KEY_VERSION = "LORE_ENCRYPTION_KEY_VERSION"
ENCRYPTION_PASSPHRASE = "LORE_ENCRYPTION_PASSPHRASE"  # noqa: S105
ENCRYPTION_PASSPHRASE_PREFIX = "LORE_ENCRYPTION_PASSPHRASE_"  # noqa: S105
ENCRYPTION_SALT = "LORE_ENCRYPTION_SALT"
ENCRYPTION_SALT_PREFIX = "LORE_ENCRYPTION_SALT_"
FEDERATION_NODE_ID = "LORE_FEDERATION_NODE_ID"
MAX_CONTEXT_PACK_LIMIT = "LORE_MAX_CONTEXT_PACK_LIMIT"
MAX_LIST_EVENTS_LIMIT = "LORE_MAX_LIST_EVENTS_LIMIT"
MIN_FACT_CONFIDENCE = "LORE_MIN_FACT_CONFIDENCE"
OIDC_ALLOWED_ALGS = "LORE_OIDC_ALLOWED_ALGS"
OIDC_AUDIENCE = "LORE_OIDC_AUDIENCE"
OIDC_CLOCK_SKEW_SECONDS = "LORE_OIDC_CLOCK_SKEW_SECONDS"
OIDC_HS256_SECRET = "LORE_OIDC_HS256_SECRET"  # noqa: S105
OIDC_ISSUER = "LORE_OIDC_ISSUER"
OIDC_JWKS_CACHE_TTL_SECONDS = "LORE_OIDC_JWKS_CACHE_TTL_SECONDS"
OIDC_JWKS_URL = "LORE_OIDC_JWKS_URL"
OPENAI_API_KEY = "LORE_OPENAI_API_KEY"
PGVECTOR_DSN = "LORE_PGVECTOR_DSN"
POLICY_SHADOW_MODE = "LORE_POLICY_SHADOW_MODE"
RATE_LIMIT_RPM = "LORE_RATE_LIMIT_RPM"
READ_ONLY_MODE = "LORE_READ_ONLY_MODE"
SEMANTIC_DEDUP_THRESHOLD_DEFAULT = "LORE_SEMANTIC_DEDUP_THRESHOLD_DEFAULT"
SEMANTIC_DEDUP_THRESHOLD_PREFIX = "LORE_SEMANTIC_DEDUP_THRESHOLD_"
TESTING_MODE = "LORE_TESTING_MODE"
TRANSPORT = "LORE_TRANSPORT"
TTL_DELETE_MODE = "LORE_TTL_DELETE_MODE"
TTL_SWEEP_INTERVAL_SECONDS = "LORE_TTL_SWEEP_INTERVAL_SECONDS"
VECTOR_BACKEND = "LORE_VECTOR_BACKEND"


_ALL_NAMES = (
    AUDIT_DB_PATH,
    ALLOW_INSECURE_DEV_SALT,
    ALLOW_STDIO_DEV,
    COMPLIANCE_STRICT_MODE,
    DB_PATH,
    DR_SNAPSHOT_DIR,
    EMBEDDING_DIM,
    EMBEDDING_MODEL,
    EMBEDDING_PROVIDER,
    EMBEDDING_WORKERS,
    EMBEDDING_TIMEOUT_SECONDS,
    ENABLE_AGENT_PERMISSIONS,
    ENABLE_MULTI_TENANT,
    ENABLE_SEMANTIC_DEDUP,
    ENCRYPTION_KEY_VERSION,
    ENCRYPTION_PASSPHRASE,
    ENCRYPTION_SALT,
    FEDERATION_NODE_ID,
    MAX_CONTEXT_PACK_LIMIT,
    MAX_LIST_EVENTS_LIMIT,
    MIN_FACT_CONFIDENCE,
    OIDC_ALLOWED_ALGS,
    OIDC_AUDIENCE,
    OIDC_CLOCK_SKEW_SECONDS,
    OIDC_HS256_SECRET,
    OIDC_ISSUER,
    OIDC_JWKS_CACHE_TTL_SECONDS,
    OIDC_JWKS_URL,
    OPENAI_API_KEY,
    PGVECTOR_DSN,
    POLICY_SHADOW_MODE,
    RATE_LIMIT_RPM,
    READ_ONLY_MODE,
    SEMANTIC_DEDUP_THRESHOLD_DEFAULT,
    TRANSPORT,
    TTL_DELETE_MODE,
    TTL_SWEEP_INTERVAL_SECONDS,
    VECTOR_BACKEND,
)

_ALL_PREFIXES = (
    ENCRYPTION_PASSPHRASE_PREFIX,
    ENCRYPTION_SALT_PREFIX,
    SEMANTIC_DEDUP_THRESHOLD_PREFIX,
)


def all_names() -> tuple[str, ...]:
    return _ALL_NAMES


def all_prefixes() -> tuple[str, ...]:
    return _ALL_PREFIXES
