"""Canonical environment variable names used across orenyl."""

from __future__ import annotations

import os
from collections.abc import Mapping

LEGACY_PREFIX = "LORE_"

AUDIT_DB_PATH = "ORENYL_AUDIT_DB_PATH"
ALLOW_INSECURE_DEV_SALT = "ORENYL_ALLOW_INSECURE_DEV_SALT"
ALLOW_STDIO_DEV = "ORENYL_ALLOW_STDIO_DEV"
COMPLIANCE_STRICT_MODE = "ORENYL_COMPLIANCE_STRICT_MODE"
DB_PATH = "ORENYL_DB_PATH"
DR_SNAPSHOT_DIR = "ORENYL_DR_SNAPSHOT_DIR"
EMBEDDING_DIM = "ORENYL_EMBEDDING_DIM"
EMBEDDING_MODEL = "ORENYL_EMBEDDING_MODEL"
EMBEDDING_PROVIDER = "ORENYL_EMBEDDING_PROVIDER"
EMBEDDING_WORKERS = "ORENYL_EMBEDDING_WORKERS"
EMBEDDING_TIMEOUT_SECONDS = "ORENYL_EMBEDDING_TIMEOUT_SECONDS"
ENABLE_AGENT_PERMISSIONS = "ORENYL_ENABLE_AGENT_PERMISSIONS"
ENABLE_MULTI_TENANT = "ORENYL_ENABLE_MULTI_TENANT"
ENABLE_SEMANTIC_DEDUP = "ORENYL_ENABLE_SEMANTIC_DEDUP"
ENCRYPTION_KEY_VERSION = "ORENYL_ENCRYPTION_KEY_VERSION"
ENCRYPTION_PASSPHRASE = "ORENYL_ENCRYPTION_PASSPHRASE"  # noqa: S105
ENCRYPTION_PASSPHRASE_PREFIX = "ORENYL_ENCRYPTION_PASSPHRASE_"  # noqa: S105
ENCRYPTION_SALT = "ORENYL_ENCRYPTION_SALT"
ENCRYPTION_SALT_PREFIX = "ORENYL_ENCRYPTION_SALT_"
FEDERATION_NODE_ID = "ORENYL_FEDERATION_NODE_ID"
MAX_CONTEXT_PACK_LIMIT = "ORENYL_MAX_CONTEXT_PACK_LIMIT"
MAX_LIST_EVENTS_LIMIT = "ORENYL_MAX_LIST_EVENTS_LIMIT"
MIN_FACT_CONFIDENCE = "ORENYL_MIN_FACT_CONFIDENCE"
OIDC_ALLOWED_ALGS = "ORENYL_OIDC_ALLOWED_ALGS"
OIDC_AUDIENCE = "ORENYL_OIDC_AUDIENCE"
OIDC_CLOCK_SKEW_SECONDS = "ORENYL_OIDC_CLOCK_SKEW_SECONDS"
OIDC_HS256_SECRET = "ORENYL_OIDC_HS256_SECRET"  # noqa: S105
OIDC_ISSUER = "ORENYL_OIDC_ISSUER"
OIDC_JWKS_CACHE_TTL_SECONDS = "ORENYL_OIDC_JWKS_CACHE_TTL_SECONDS"
OIDC_JWKS_URL = "ORENYL_OIDC_JWKS_URL"
OPENAI_API_KEY = "ORENYL_OPENAI_API_KEY"
PGVECTOR_DSN = "ORENYL_PGVECTOR_DSN"
POLICY_SHADOW_MODE = "ORENYL_POLICY_SHADOW_MODE"
RATE_LIMIT_RPM = "ORENYL_RATE_LIMIT_RPM"
READ_ONLY_MODE = "ORENYL_READ_ONLY_MODE"
SEMANTIC_DEDUP_THRESHOLD_DEFAULT = "ORENYL_SEMANTIC_DEDUP_THRESHOLD_DEFAULT"
SEMANTIC_DEDUP_THRESHOLD_PREFIX = "ORENYL_SEMANTIC_DEDUP_THRESHOLD_"
TESTING_MODE = "ORENYL_TESTING_MODE"
TRANSPORT = "ORENYL_TRANSPORT"
TTL_DELETE_MODE = "ORENYL_TTL_DELETE_MODE"
TTL_SWEEP_INTERVAL_SECONDS = "ORENYL_TTL_SWEEP_INTERVAL_SECONDS"
VECTOR_BACKEND = "ORENYL_VECTOR_BACKEND"


_ALL_NAMES = (
    AUDIT_DB_PATH,
    ALLOW_INSECURE_DEV_SALT,
    ALLOW_STDIO_DEV,
    COMPLIANCE_STRICT_MODE,
    DB_PATH,
    DR_SNAPSHOT_DIR,
    EMBEDDING_DIM,
    EMBEDDING_MODEL,
    EMBEDDING_PROVIDER,
    EMBEDDING_WORKERS,
    EMBEDDING_TIMEOUT_SECONDS,
    ENABLE_AGENT_PERMISSIONS,
    ENABLE_MULTI_TENANT,
    ENABLE_SEMANTIC_DEDUP,
    ENCRYPTION_KEY_VERSION,
    ENCRYPTION_PASSPHRASE,
    ENCRYPTION_SALT,
    FEDERATION_NODE_ID,
    MAX_CONTEXT_PACK_LIMIT,
    MAX_LIST_EVENTS_LIMIT,
    MIN_FACT_CONFIDENCE,
    OIDC_ALLOWED_ALGS,
    OIDC_AUDIENCE,
    OIDC_CLOCK_SKEW_SECONDS,
    OIDC_HS256_SECRET,
    OIDC_ISSUER,
    OIDC_JWKS_CACHE_TTL_SECONDS,
    OIDC_JWKS_URL,
    OPENAI_API_KEY,
    PGVECTOR_DSN,
    POLICY_SHADOW_MODE,
    RATE_LIMIT_RPM,
    READ_ONLY_MODE,
    SEMANTIC_DEDUP_THRESHOLD_DEFAULT,
    TRANSPORT,
    TTL_DELETE_MODE,
    TTL_SWEEP_INTERVAL_SECONDS,
    VECTOR_BACKEND,
)

_ALL_PREFIXES = (
    ENCRYPTION_PASSPHRASE_PREFIX,
    ENCRYPTION_SALT_PREFIX,
    SEMANTIC_DEDUP_THRESHOLD_PREFIX,
)


def all_names() -> tuple[str, ...]:
    return _ALL_NAMES


def all_prefixes() -> tuple[str, ...]:
    return _ALL_PREFIXES


def detect_legacy_names(environ: Mapping[str, str] | None = None) -> tuple[str, ...]:
    source = environ if environ is not None else os.environ
    return tuple(sorted(name for name in source if name.startswith(LEGACY_PREFIX)))


def require_no_legacy_env_vars(environ: Mapping[str, str] | None = None) -> None:
    legacy_names = detect_legacy_names(environ)
    if legacy_names:
        legacy_list = ", ".join(legacy_names)
        raise RuntimeError(
            f"legacy environment variables are not supported: {legacy_list}"
        )
